/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "IdManager.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

register_and_get_id_result *
registerandgetid_1(ProcessInformation *argp, CLIENT *clnt)
{
	static register_and_get_id_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTERANDGETID,
		(xdrproc_t) xdr_ProcessInformation, (caddr_t) argp,
		(xdrproc_t) xdr_register_and_get_id_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

get_processes_result *
getprocesses_1(int *argp, CLIENT *clnt)
{
	static get_processes_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETPROCESSES,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_get_processes_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

unregister_result *
unregister_1(int *argp, CLIENT *clnt)
{
	static unregister_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UNREGISTER,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_unregister_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
