/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IdManager.h"


void
idmanager_1(char *host)
{
	CLIENT *clnt;
	register_and_get_id_result  *result_1;
	ProcessInformation  registerandgetid_1_arg;
	get_processes_result  *result_2;
	int  getprocesses_1_arg;
	unregister_result  *result_3;
	int  unregister_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, IDMANAGER, ver1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registerandgetid_1(&registerandgetid_1_arg, clnt);
	if (result_1 == (register_and_get_id_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = getprocesses_1(&getprocesses_1_arg, clnt);
	if (result_2 == (get_processes_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = unregister_1(&unregister_1_arg, clnt);
	if (result_3 == (unregister_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	idmanager_1 (host);
exit (0);
}
