/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IdManager.h"

bool_t
xdr_ProcessInformation (XDR *xdrs, ProcessInformation *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->processType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->processId))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->address, ADDRESS_LENGHT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->running))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_register_and_get_id_result (XDR *xdrs, register_and_get_id_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_int (xdrs, &objp->register_and_get_id_result_u.processId))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_get_processes_result (XDR *xdrs, get_processes_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_array (xdrs, (char **)&objp->get_processes_result_u.processes.processes_val, (u_int *) &objp->get_processes_result_u.processes.processes_len, ~0,
			sizeof (ProcessInformation), (xdrproc_t) xdr_ProcessInformation))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_unregister_result (XDR *xdrs, unregister_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_int (xdrs, &objp->unregister_result_u.processId))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
